GLEXTFUNC(void, glBlendEquation, (GLenum))
GLEXTFUNC(void, glBlendFuncSeparate, (GLenum, GLenum, GLenum, GLenum))
GLEXTFUNC(void, glMultiDrawArrays, (GLenum, const GLint *, const GLsizei *, GLsizei))
GLEXTFUNC(void, glMultiDrawElements, (GLenum, const GLsizei *, GLenum, const void *const *, GLsizei))
GLEXTFUNC(void, glClipControl, (GLenum, GLenum))

GLEXTFUNC(void, glCreateBuffers, (GLsizei, GLuint *))
GLEXTFUNC(void, glDeleteBuffers, (GLsizei, const GLuint *))
GLEXTFUNC(void, glBindBuffer, (GLenum, GLuint))
GLEXTFUNC(void, glBindBufferBase, (GLenum, GLuint, GLuint))
GLEXTFUNC(void, glNamedBufferData, (GLuint,	GLsizeiptr, const void *, GLenum))
GLEXTFUNC(void, glNamedBufferSubData, (GLuint, GLintptr, GLsizeiptr, const void *))
GLEXTFUNC(void *, glMapNamedBuffer, (GLuint, GLenum))
GLEXTFUNC(GLboolean, glUnmapNamedBuffer, (GLuint))

GLEXTFUNC(void, glCreateVertexArrays, (GLsizei, GLuint *))
GLEXTFUNC(void, glDeleteVertexArrays, (GLsizei, const GLuint *))
GLEXTFUNC(void, glBindVertexArray, (GLuint))
GLEXTFUNC(void, glEnableVertexArrayAttrib, (GLuint, GLuint))
GLEXTFUNC(void, glDisableVertexArrayAttrib, (GLuint, GLuint))
GLEXTFUNC(void, glVertexArrayAttribFormat, (GLuint, GLuint, GLint, GLenum, GLboolean, GLuint))
GLEXTFUNC(void, glVertexArrayVertexBuffer, (GLuint, GLuint, GLuint, GLintptr, GLsizei))
GLEXTFUNC(void, glVertexArrayAttribBinding, (GLuint, GLuint, GLuint))

GLEXTFUNC(void, glCreateTextures, (GLenum, GLsizei, GLuint *))
GLEXTFUNC(void, glBindTextures, (GLuint, GLsizei, const GLuint *))
GLEXTFUNC(void, glTextureStorage2D, (GLuint, GLsizei, GLenum, GLsizei, GLsizei))
GLEXTFUNC(void, glTextureStorage3D, (GLuint, GLsizei, GLenum, GLsizei, GLsizei, GLsizei))
GLEXTFUNC(void, glTextureStorage2DMultisample, (GLuint, GLsizei, GLenum, GLsizei, GLsizei, GLboolean))
GLEXTFUNC(void, glTextureSubImage2D, (GLuint, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const void *))
GLEXTFUNC(void, glTextureSubImage3D, (GLuint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const void *))
GLEXTFUNC(void, glCompressedTextureSubImage2D, (GLuint, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const void *))
GLEXTFUNC(void, glCompressedTextureSubImage3D, (GLuint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const void *))
GLEXTFUNC(void, glTextureParameterf, (GLuint, GLenum, float))
GLEXTFUNC(void, glTextureParameterfv, (GLuint, GLenum, const float *))
GLEXTFUNC(void, glTextureParameteri, (GLuint, GLenum, int))
GLEXTFUNC(void, glTextureParameteriv, (GLuint, GLenum, const int *))

GLEXTFUNC(void, glCreateFramebuffers, (GLsizei, GLuint *))
GLEXTFUNC(void, glDeleteFramebuffers, (GLsizei, GLuint *))
GLEXTFUNC(void, glBindFramebuffer, (GLenum, GLuint))
GLEXTFUNC(void, glBlitNamedFramebuffer, (GLuint, GLuint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLbitfield, GLenum))
GLEXTFUNC(void, glNamedFramebufferTexture, (GLuint, GLenum, GLuint, GLint))
GLEXTFUNC(void, glNamedFramebufferTextureLayer, (GLuint, GLenum, GLuint, GLint, GLint))
GLEXTFUNC(void, glNamedFramebufferDrawBuffers, (GLuint, GLsizei, const GLenum *))
GLEXTFUNC(void, glNamedFramebufferReadBuffer, (GLuint, GLenum))
GLEXTFUNC(void, glClearNamedFramebufferfv, (GLuint, GLenum, GLint, const GLfloat *))

GLEXTFUNC(GLuint, glCreateShader, (GLenum))
GLEXTFUNC(void, glDeleteShader, (GLuint))
GLEXTFUNC(void, glShaderSource, (GLuint, GLsizei, const GLchar **, const GLint *))
GLEXTFUNC(void, glCompileShader, (GLuint))
GLEXTFUNC(void, glAttachShader, (GLuint, GLuint))
GLEXTFUNC(GLuint, glCreateProgram, (void))
GLEXTFUNC(void, glDeleteProgram, (GLuint))
GLEXTFUNC(void, glLinkProgram, (GLuint))
GLEXTFUNC(void, glUseProgram, (GLuint))
GLEXTFUNC(void, glProgramUniform4fv, (GLuint, GLint, GLsizei, const GLfloat *))
GLEXTFUNC(void, glGetShaderiv, (GLuint, GLenum, GLint *))
GLEXTFUNC(void, glGetProgramiv, (GLuint, GLenum, GLint *))
GLEXTFUNC(void, glGetShaderInfoLog, (GLuint, GLsizei, GLsizei *, GLchar *))
GLEXTFUNC(void, glGetProgramInfoLog, (GLuint, GLsizei, GLsizei *, GLchar *))

GLEXTFUNC(void, glGenQueries, (GLsizei, GLuint *))
GLEXTFUNC(void, glDeleteQueries, (GLsizei, const GLuint *))
GLEXTFUNC(void, glBeginQuery, (GLenum, GLuint))
GLEXTFUNC(void, glEndQuery, (GLenum))
GLEXTFUNC(void, glGetQueryObjectui64v, (GLuint, GLenum, GLuint64 *))

GLEXTFUNC(BOOL, wglChoosePixelFormatARB, (HDC, const int *, const FLOAT *, UINT, int *, UINT *))
GLEXTFUNC(HGLRC, wglCreateContextAttribsARB, (HDC, HGLRC, const int *))
GLEXTFUNC(BOOL, wglSwapIntervalEXT, (int))
